### PR TITLE
Update linking rule

### PR DESCRIPTION
**Pull request by duboff**
I copied the changes from our Auth0 instance here so we can keep track of everything better.

### CODE REVIEW

**Comment by monsha** [comment]
@duboff we cant query with `toLowerCase` because in case of trainline users for example, their emails can be capitalized on auth0.

> When using this endpoint (/users-by-email), make sure that you are searching for users via email addresses using the correct case.

For example, I tried:
```
curl --request GET \
  --url 'https://chattermill.eu.auth0.com/api/v2/users-by-email?email=peter.wade@thetrainline.com' \
  --header 'authorization: Bearer <token>
```

and the result was empty.

**Comment by OpakAlex** [comment]
i agree with @monsha. We can not search with `toLowerCase`.

**Comment by monsha** [comment]
@duboff I think there isn't problem with linking accounts (the rule doesnt remove users/identities). Anyway I tried several uses cases linking accounts, and the rule works ok, It links google-acount with auth0 and viceversa

**Comment by duboff** [comment]
Cool, @monsha I would still want to use Github from now on instead of editing code on Auth0. Is this OK to deploy?

**Comment by monsha** [comment]
@duboff this https://github.com/chattermill/cm-auth0/blob/9f01737ef4e49c24f968fb224b2ad632d8271802/rules/link-accounts-with-same-email.js#L43 won't work for SSO flag enabled accounts, because that condition will always return `Auth0 profile was not found for ...` on Authentication, due to they dont have auth0 accounts (baseProfile)

**Comment by duboff** [comment]
@monsha Better?

**Comment by monsha** [comment]
👍

**Pull request merged**
